"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "ar" | "fr" | "en";

interface AppContextType {
  darkMode: boolean;
  setDarkMode: (v: boolean) => void;
  lang: Lang;
  setLang: (v: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  ar: {
    appName: "Skool Manager",
    welcome: "مرحباً بك، المدير",
    login: "تسجيل الدخول",
    email: "الإيميل",
    password: "كلمة السر",
    enter: "دخول",
    loading: "جاري الدخول...",
    wrongCredentials: "إيميل أو كلمة السر غلط!",
    students: "التلاميذ",
    absences: "الغياب",
    grades: "النقط",
    classes: "الأقسام",
    users: "المستخدمين",
    messages: "الرسائل",
    dashboard: "لوحة التحكم",
    back: "رجوع",
    add: "إضافة",
    save: "حفظ",
    delete: "حذف",
    register: "تسجيل",
    send: "إرسال",
    name: "الاسم",
    lastname: "النسب",
    class: "الفصل",
    subject: "المادة",
    grade: "النقطة",
    date: "التاريخ",
    student: "التلميذ",
    teacher: "الأستاذ",
    parent: "الولي",
    admin: "مدير",
    role: "الدور",
    level: "المستوى",
    className: "اسم القسم",
    newStudent: "إضافة تلميذ جديد",
    newAbsence: "تسجيل غياب",
    newGrade: "إدخال نقطة",
    newClass: "إضافة قسم جديد",
    newUser: "إضافة مستخدم جديد",
    newMessage: "رسالة جديدة",
    receiver: "اختار المستلم",
    writeMessage: "اكتب رسالتك هنا...",
    studentsList: "قائمة التلاميذ",
    absencesList: "سجل الغياب",
    gradesList: "سجل النقط",
    classesList: "قائمة الأقسام",
    usersList: "قائمة المستخدمين",
    conversations: "المحادثات",
    noStudents: "لا يوجد تلاميذ بعد",
    noAbsences: "لا يوجد غياب مسجل",
    noGrades: "لا يوجد نقط مسجلة",
    noClasses: "لا يوجد أقسام بعد",
    noUsers: "لا يوجد مستخدمين بعد",
    noMessages: "لا توجد رسائل بعد",
    noNotifications: "لا توجد تنبيهات جديدة",
    search: "ابحث عن تلميذ...",
    monthlyRevenue: "المداخيل الشهرية",
    recentAlerts: "آخر التنبيهات",
    quickActions: "إجراءات سريعة",
    totalStudents: "التلاميذ",
    totalTeachers: "الأساتذة",
    todayAbsences: "غياب اليوم",
    monthRevenue: "المداخيل",
    logout: "خروج",
    teacherBoard: "لوحة الأستاذ",
    parentBoard: "لوحة الولي",
    me: "أنا",
    absence: "غياب",
    paid: "خالص",
    unpaid: "لم يسدد",
    partial: "دفع جزئي",
    monthlyTracker: "تتبع الواجب الشهري",
    amount: "المبلغ",
    update: "تحديث",
    paidAmount: "المبلغ المدفوع",
    remaining: "المتبقي",
    average: "معدل",
    successAdd: "✅ تمت الإضافة بنجاح!",
    selectStudent: "اختار التلميذ",
    selectTeacher: "اختار الأستاذ",
  },
  fr: {
    appName: "Skool Manager",
    welcome: "Bienvenue, Directeur",
    login: "Connexion",
    email: "Email",
    password: "Mot de passe",
    enter: "Connexion",
    loading: "Connexion en cours...",
    wrongCredentials: "Email ou mot de passe incorrect!",
    students: "Élèves",
    absences: "Absences",
    grades: "Notes",
    classes: "Classes",
    users: "Utilisateurs",
    messages: "Messages",
    dashboard: "Tableau de bord",
    back: "Retour",
    add: "Ajouter",
    save: "Enregistrer",
    delete: "Supprimer",
    register: "Enregistrer",
    send: "Envoyer",
    name: "Prénom",
    lastname: "Nom",
    class: "Classe",
    subject: "Matière",
    grade: "Note",
    date: "Date",
    student: "Élève",
    teacher: "Professeur",
    parent: "Parent",
    admin: "Directeur",
    role: "Rôle",
    level: "Niveau",
    className: "Nom de classe",
    newStudent: "Ajouter un élève",
    newAbsence: "Enregistrer une absence",
    newGrade: "Saisir une note",
    newClass: "Ajouter une classe",
    newUser: "Ajouter un utilisateur",
    newMessage: "Nouveau message",
    receiver: "Choisir le destinataire",
    writeMessage: "Écrivez votre message...",
    studentsList: "Liste des élèves",
    absencesList: "Registre des absences",
    gradesList: "Registre des notes",
    classesList: "Liste des classes",
    usersList: "Liste des utilisateurs",
    conversations: "Conversations",
    noStudents: "Aucun élève enregistré",
    noAbsences: "Aucune absence enregistrée",
    noGrades: "Aucune note enregistrée",
    noClasses: "Aucune classe enregistrée",
    noUsers: "Aucun utilisateur enregistré",
    noMessages: "Aucun message",
    noNotifications: "Aucune nouvelle notification",
    search: "Rechercher un élève...",
    monthlyRevenue: "Revenus mensuels",
    recentAlerts: "Dernières alertes",
    quickActions: "Actions rapides",
    totalStudents: "Élèves",
    totalTeachers: "Professeurs",
    todayAbsences: "Absences aujourd'hui",
    monthRevenue: "Revenus",
    logout: "Déconnexion",
    teacherBoard: "Tableau professeur",
    parentBoard: "Tableau parent",
    me: "Moi",
    absence: "Absence",
    paid: "Payé",
    unpaid: "Non payé",
    partial: "Partiel",
    monthlyTracker: "Suivi mensuel",
    amount: "Montant",
    update: "Mettre à jour",
    paidAmount: "Montant payé",
    remaining: "Reste",
    average: "Moyenne",
    successAdd: "✅ Ajout réussi!",
    selectStudent: "Choisir l'élève",
    selectTeacher: "Choisir le professeur",
  },
  en: {
    appName: "Skool Manager",
    welcome: "Welcome, Director",
    login: "Login",
    email: "Email",
    password: "Password",
    enter: "Sign In",
    loading: "Signing in...",
    wrongCredentials: "Wrong email or password!",
    students: "Students",
    absences: "Absences",
    grades: "Grades",
    classes: "Classes",
    users: "Users",
    messages: "Messages",
    dashboard: "Dashboard",
    back: "Back",
    add: "Add",
    save: "Save",
    delete: "Delete",
    register: "Register",
    send: "Send",
    name: "First Name",
    lastname: "Last Name",
    class: "Class",
    subject: "Subject",
    grade: "Grade",
    date: "Date",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
    admin: "Director",
    role: "Role",
    level: "Level",
    className: "Class Name",
    newStudent: "Add New Student",
    newAbsence: "Record Absence",
    newGrade: "Enter Grade",
    newClass: "Add New Class",
    newUser: "Add New User",
    newMessage: "New Message",
    receiver: "Choose Recipient",
    writeMessage: "Write your message...",
    studentsList: "Students List",
    absencesList: "Absences Register",
    gradesList: "Grades Register",
    classesList: "Classes List",
    usersList: "Users List",
    conversations: "Conversations",
    noStudents: "No students yet",
    noAbsences: "No absences recorded",
    noGrades: "No grades recorded",
    noClasses: "No classes yet",
    noUsers: "No users yet",
    noMessages: "No messages yet",
    noNotifications: "No new notifications",
    search: "Search student...",
    monthlyRevenue: "Monthly Revenue",
    recentAlerts: "Recent Alerts",
    quickActions: "Quick Actions",
    totalStudents: "Students",
    totalTeachers: "Teachers",
    todayAbsences: "Today's Absences",
    monthRevenue: "Revenue",
    logout: "Logout",
    teacherBoard: "Teacher Dashboard",
    parentBoard: "Parent Dashboard",
    me: "Me",
    absence: "Absence",
    paid: "Paid",
    unpaid: "Unpaid",
    partial: "Partial",
    monthlyTracker: "Monthly Tracker",
    amount: "Amount",
    update: "Update",
    paidAmount: "Amount Paid",
    remaining: "Remaining",
    average: "Average",
    successAdd: "✅ Added successfully!",
    selectStudent: "Select Student",
    selectTeacher: "Select Teacher",
  },
};

const AppContext = createContext<AppContextType>({
  darkMode: false,
  setDarkMode: () => {},
  lang: "ar",
  setLang: () => {},
  t: (key) => key,
});

export function AppProvider({ children }: { children: ReactNode }) {
  const [darkMode, setDarkModeState] = useState(false);
  const [lang, setLangState] = useState<Lang>("ar");

  useEffect(() => {
    const savedDark = localStorage.getItem("darkMode");
    const savedLang = localStorage.getItem("lang") as Lang;
    if (savedDark) setDarkModeState(savedDark === "true");
    if (savedLang) setLangState(savedLang);
  }, []);

  const setDarkMode = (v: boolean) => {
    setDarkModeState(v);
    localStorage.setItem("darkMode", String(v));
  };

  const setLang = (v: Lang) => {
    setLangState(v);
    localStorage.setItem("lang", v);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <AppContext.Provider value={{ darkMode, setDarkMode, lang, setLang, t }}>
      {children}
    </AppContext.Provider>
  );
}

export const useApp = () => useContext(AppContext);